# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ca06cb7e5081fdbd4bde8cbd11da64e"
name = "Gleura Chat Support"
application_url = "https://j2paxwkmmd.eu-central-1.awsapprunner.com/"
embedded = true
handle = "gleura-chat-support"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://j2paxwkmmd.eu-central-1.awsapprunner.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://j2paxwkmmd.eu-central-1.awsapprunner.com/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_all_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://j2paxwkmmd.eu-central-1.awsapprunner.com/auth/callback",
  "https://j2paxwkmmd.eu-central-1.awsapprunner.com/auth/shopify/callback"
]

[app_proxy]
url = "https://j2paxwkmmd.eu-central-1.awsapprunner.com/api/chat"
subpath = "chat"
prefix = "apps"

[pos]
embedded = false
